---
title: "apartments_model"
author: "Arnold Kakaš"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

create and evaluate models

```{r message=FALSE, warning=FALSE}
# import libs
if (!require("pacman")) {
  install.packages("pacman")
}

pacman::p_load(
  sf,
  tidyverse,
  tidymodels,
  GGally,
  #mice,
  #patchwork,
  vip,
  SHAPforxgboost,
  parallel,
  dataPreparation,
  doParallel,
  extrafont
)
loadfonts(device = "win")
```


```{r}
# import data
apartments_analysis_data <- readRDS("data/apartments_final_data.rds") |>
  filter(!is.na(price)) |>
  mutate(
    coord = st_coordinates(st_centroid(geometry)),
    lon = coord[, 1],
    lat = coord[, 2]
  ) |>
  select(-coord) # Optionally remove the original coordinates column

# remove geometry since we have coordinates now
apartments_analysis_data$geometry <- NULL

saveRDS(apartments_analysis_data, "data/apartments_data_App.RDS")
```



```{r}
# split dataframes to train(80)/test(20)
set.seed(123)
apartments_train_split <- initial_split(apartments_analysis_data, prop = 0.7, strata = price)

apartments_train <- training(apartments_train_split)
apartments_test <- testing(apartments_train_split)

saveRDS(apartments_test, "data/apartments_test.RDS")


folds <- vfold_cv(apartments_train, v = 5, strata = price)
```

```{r}
# recipes
apartments_xgboost_recipe <- recipe(apartments_train, price ~ .) |>
  step_rm(name_nsi) |>
  step_string2factor(all_nominal_predictors()) |>
  step_impute_knn(all_nominal_predictors()) |>
  step_unknown(all_nominal_predictors()) |>
  step_dummy(all_nominal_predictors())
```


```{r}
# models
xgb_model <-
  boost_tree(
    trees = tune(), loss_reduction = tune(),
    tree_depth = tune(), min_n = tune(),
    mtry = tune(), sample_size = tune(),
    learn_rate = tune()
  ) |>
  set_mode("regression") |>
  set_engine("xgboost")
```

```{r}
# workflows
apartments_workflow <- workflow() |>
  add_recipe(apartments_xgboost_recipe) |>
  add_model(xgb_model)
```

```{r}
# parameters
apartments_xgboost_params <- parameters(
  trees(), learn_rate(), loss_reduction(),
  tree_depth(), min_n(),
  sample_size = sample_prop(),
  finalize(mtry(), apartments_train)
)

apartments_xgboost_params <- apartments_xgboost_params %>% update(trees = trees(c(300, 600)))
```

```{r}
# optimization

registerDoParallel(cores = detectCores() - 2)

xgboost_tune <-
  apartments_workflow %>%
  tune_bayes(
    resamples = folds,
    param_info = apartments_xgboost_params,
    iter = 30,
    metrics = metric_set(rmse, mape),
    control = control_bayes(
      no_improve = 10,
      save_pred = T, verbose = F
    )
  )

# doParallel::stopImplicitCluster()
autoplot(xgboost_tune)
```

```{r}
# best models
apartments_best_model <- select_best(xgboost_tune, "rmse")
```

```{r}
# finalize models
apartments_final_model <- finalize_model(xgb_model, apartments_best_model)
apartments_workflow <- apartments_workflow |> update_model(apartments_final_model)
apartments_xgb_fit <- fit(apartments_workflow, data = apartments_train)

saveRDS(apartments_xgb_fit, "data/xgb_fit.RDS")
apartments_xgb_fit <- readRDS("data/xgb_fit.RDS")
```

```{r}
apartments_xgb_fit |>
  fit(data = apartments_train) |>
  pull_workflow_fit() |>
  vip(geom = "point", include_type = TRUE) + 
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    text = element_text(family = "Courier New", size = 12)
  ) + 
  labs(
    y = "Dôležitosť",
    x = "Premenná"
  )
```


```{r message=FALSE, warning=FALSE, fig.width=8}
#| fig-height: 28
fitted_data <- apartments_xgboost_recipe %>%
  prep() %>%
  bake(new_data = apartments_analysis_data) %>%
  select(-price)

shap_long <- shap.prep(xgb_model = extract_fit_engine(apartments_xgb_fit), 
                        X_train = fitted_data %>% as.matrix(), top_n = 15) |> 
  mutate(mean_value = round(mean_value, 0))
                       
shap_plot <- shap.plot.summary(shap_long, scientific = FALSE) +
  geom_text(data = unique(shap_long[, c("variable", "mean_value")]),
            aes(x = variable, y = -Inf, label = format(mean_value, big.mark = " ", scientific = FALSE)),
            size = 3, alpha = 0.7,
            hjust = -0.2,
            check_overlap = TRUE,
            family = "Courier New") +
  scale_y_continuous(labels = function(x) format(x, big.mark = " ", scientific = FALSE)) +
  scale_color_gradient(low = "blue", high = "red",
                      breaks = c(0,1),
                      labels = c("nízka", "vysoká"),
                      guide = guide_colorbar(barwidth = 12, barheight = 0.3)) + # Customize based on your exact needs
  labs(x = "Premenná",
       y = "SHAP hodnota (vplyv na predikovanú cenu)",
       color = "Hodnota premennej  "
       ) +
  theme(
    panel.grid.minor = element_blank(),
    text = element_text(family = "Courier New", size = 12),
    legend.position = "bottom"
  )

shap_plot$layers[[3]] <- NULL

shap_plot
```

```{r message=FALSE, warning=FALSE}
apartments_final_res <- last_fit(apartments_xgb_fit, apartments_train_split)
collect_metrics(apartments_final_res) |> mutate(.estimate = round(.estimate, 2))
```

```{r message=FALSE, warning=FALSE}
# evaluate
apartments_pred <-
  predict(apartments_xgb_fit, apartments_test) |>
  bind_cols(apartments_test)

apartments_plot1 <-
  apartments_pred |>
  ggplot(aes(x = .pred, y = price)) +
  geom_point() +
  geom_smooth(method = "loess", color = "red") +
  scale_y_continuous(labels = function(x) format(x, big.mark = " ", scientific = FALSE), breaks = c(200000, 400000, 600000)) +
  scale_x_continuous(labels = function(x) format(x, big.mark = " ", scientific = FALSE), breaks = c(200000, 400000, 600000)) +
  labs(
    title = NULL,
    x = "Predikovaná cena",
    y = "Reálna Cena"
  ) +
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    text = element_text(family = "Courier New", size = 12)
  ) +
  # coord_cartesian(xlim = c(0,300000)) +
  coord_fixed()


apartments_plot2 <-
  apartments_pred |>
  select(predikcia = .pred, realita = price) |>
  gather(key, value) |>
  ggplot(aes(x = value, color = key)) +
  geom_density(alpha = .2) +
  labs(
    title = NULL,
    x = "Cena",
    y = "Hustota",
    color = ""
  ) +
  scale_y_continuous(labels = function(x) format(x, big.mark = " ", scientific = FALSE)) +
  scale_x_continuous(labels = function(x) format(x, big.mark = " ", scientific = FALSE)) +
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    text = element_text(family = "Courier New", size = 12)
  )
  # coord_cartesian(xlim = c(0,600000))

  apartments_plot1
```

```{r}
# save model
saveRDS(apartments_xgb_fit, "data/model.RDS")

# save other data for app
conditions <- apartments_analysis_data |>
  select(condition) |>
  distinct()
saveRDS(conditions, "data/conditions.RDS")

certificate <- apartments_analysis_data |>
  select(certificate) |>
  distinct()
saveRDS(certificate, "data/certificate.RDS")

type <- apartments_analysis_data |>
  select(type) |>
  distinct()
saveRDS(type, "data/type.RDS")
```

```{r}
test <- data.frame(
  name_nsi = "Senec",
  district = "Bratislava I",
  index = 10,
  condition = "New building",
  area = 182,
  provision = 0,
  certificate = "A",
  type = "5-room apartment",
  rooms = 5,
  environment = 10,
  quality_of_living = 10,
  safety = 10,
  transport = 10,
  services = 10,
  relax = 10,
  lon = 18.1,
  lat = 45.2
)


predict(apartments_xgb_fit, test)
```
