---
title: "consolidate"
author: "Arnold Kakaš"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Consolidate data scraped from web and geospatial data

```{r}
# import libraries
if (!require("pacman")) {
  install.packages("pacman")
}

pacman::p_load(
  tidyverse,
  janitor,
  skimr,
  DataExplorer,
  sf,
  ggmap,
  colorRamps,
  plotly,
  spdep,
  #rgeos,
  #rgdal,
  sfdep
)
```

```{r}
# load data
advertisements <- readRDS("data/advertisements.RDS")
advertisements <- advertisements %>% separate(type_of_real_estate, c("type", "area"), sep = " • ", remove = TRUE) %>% select(link, type)


scraped_data <- readRDS("data/advertisements_complete_geocoded.RDS") %>% 
  left_join(advertisements, by = "link", multiple = "first", keep = FALSE) %>% 
  clean_names() %>%
  mutate(pocet_izieb_miestnosti = as.numeric(pocet_izieb_miestnosti),
         uzit_plocha = str_replace(str_replace(uzit_plocha, ",", "."), " m2", ""),
         energie = str_replace(str_replace(energie, ",", "."), " €/mesiac", ""),
         provizia_zahrnuta_v_cene = str_replace_na(provizia_zahrnuta_v_cene, "Nie"),
         rooms = case_when(type == "1 izbový byt" ~ 1,
                           type == "2 izbový byt" ~ 2,
                           type == "3 izbový byt" ~ 3,
                           type == "4 izbový byt" ~ 4,
                           type == "5 a viac izbový byt" ~ 5,
                           type == "Garsónka" ~ 1,
                           type == "Dvojgarsónka" ~ 2, 
                           .default = NA),
         pocet_izieb_miestnosti = coalesce(pocet_izieb_miestnosti, rooms, pocet_izieb_miestnosti)) %>% 
  mutate_at(c('index_of_living',
              'uzit_plocha',
              'energie',
              'pocet_nadzemnych_podlazi', 
              'podlazie', 
              'pocet_izieb_miestnosti', 
              'rok_vystavby', 
              'rok_poslednej_rekonstrukcie', 
              'pocet_balkonov', 
              'pocet_lodzii'), as.numeric) %>% 
  select(-link, -info_text, -address) %>% 
  filter(pocet_izieb_miestnosti < 10 & !is.na(pocet_izieb_miestnosti)) %>% 
  mutate(
         type = coalesce(type, case_when(pocet_izieb_miestnosti == 1 ~ "1 izbový byt",
                           pocet_izieb_miestnosti == 2 ~ "2 izbový byt",
                           pocet_izieb_miestnosti == 3 ~ "3 izbový byt",
                           pocet_izieb_miestnosti == 4 ~ "4 izbový byt",
                           pocet_izieb_miestnosti >= 5 ~ "5 a viac izbový byt"))) %>% 
  select(-rooms) %>% 
  filter(!(type %in% c("Apartmán", "Mezonet", "Iný byt", "Loft"))) %>% 
  mutate(rooms = case_when(type == "1 izbový byt" ~ 1,
                           type == "2 izbový byt" ~ 2,
                           type == "3 izbový byt" ~ 3,
                           type == "4 izbový byt" ~ 4,
                           type == "5 a viac izbový byt" ~ 5,
                           type == "Garsónka" ~ 1,
                           type == "Dvojgarsónka" ~ 2, 
                           .default = NA))

```


```{r}
scraped_cleaned <- scraped_data %>% 
  select(-c(rok_vystavby,
            rok_poslednej_rekonstrukcie,
            typ_konstrukcie,
            pocet_balkonov,
            pocet_lodzii,
            orientacia,
            energie,
            pivnica,
            vytah,
            pocet_izieb_miestnosti,
            pocet_nadzemnych_podlazi,
            podlazie)) %>% 
  rename(index = index_of_living) %>% 
  rename(condition = stav) %>% 
  rename(area = uzit_plocha) %>% 
  rename(provision = provizia_zahrnuta_v_cene) %>%
  rename(certificate = energeticky_certifikat)

scraped_cleaned_wo_geometry <- scraped_cleaned
st_geometry(scraped_cleaned_wo_geometry) <- NULL

#DataExplorer::create_report(scraped_cleaned_wo_geometry)


```


```{r}
# keep only municipalities with at least 5 ads
number_of_ads <- scraped_cleaned_wo_geometry %>% group_by(name_nsi) %>% tally() %>% arrange(n)

scraped_cleaned <- scraped_cleaned %>% 
  left_join(number_of_ads, by = "name_nsi", keep = FALSE) %>% 
  filter(n > 4)

relevant_mun <- number_of_ads %>% 
  filter(n > 4) %>% 
  select(1)

saveRDS(relevant_mun, file = "data/app_obce_filter_list.rds")

```



```{r}
# calculate mean index of district
index_district <- scraped_cleaned_wo_geometry %>% 
  filter(!is.na(price)) %>%
  group_by(name_nsi) %>% 
  mutate(index_mean_name_nsi = mean(index, na.rm = TRUE)) %>%
  ungroup() %>%
  select(name_nsi, district, index_mean_name_nsi) %>% 
  distinct() %>% 
  mutate(index_mean_name_nsi = if_else(index_mean_name_nsi > 0, index_mean_name_nsi, NA)) %>% 
  group_by(district) %>% 
  summarize(index_mean_district = mean(index_mean_name_nsi, na.rm = TRUE))
  


# scraped_cleaned_wo_outliers <- scraped_cleaned %>% 
#   filter(!is.na(price)) %>%
#   group_by(name_nsi) %>% 
#   mutate(index = mean(as.numeric(index),na.rm = TRUE),
#          index = if_else(index > 0, index, NA),
#          IQR = IQR(price),
#          median = median(price),
#          lower = median - 1.5*IQR,
#          upper = median + 1.5*IQR,
#          ) %>% 
#   ungroup() %>% 
#   filter(price >= lower & price <= upper) %>% 
#   select(-lower, -upper, -median, -IQR) %>% 
#   left_join(index_district, by = "district", multiple = "first", keep = FALSE)

scraped_cleaned_final <- scraped_cleaned %>% 
  left_join(index_district, by = "district", multiple = "first", keep = FALSE)
```


```{r}
# 
# district_mean_index <- scraped_data %>% group_by(name) %>% summarize(i = mean(as.numeric(index_of_living),na.rm = TRUE))
# 
# district_mean_index$x[is.nan(district_mean_index$i)] <- NA
# district_mean_index$x <- ifelse(district_mean_index$x == 0.000000, NA, district_mean_index$x)
# district_mean_index$x.check <- district_mean_index$x
# 
# 
# x <- 1
# n <- 5
# nb.districts <- st_contiguity(district_mean_index)
# weight <- st_weights(nb.districts)
# while (i <= n) {
# district_mean_index$lag.x <- st_lag(district_mean_index$x, nb.districts, weight, na_ok = TRUE)
# district_mean_index <- district_mean_index %>% 
#   mutate(x = coalesce(x, lag.x)) %>% 
#   select(-lag.x)
# 
# i = i + 1
# 
# }

```

```{r}
rm(list = setdiff(ls(), "scraped_cleaned_final")) #scraped_cleaned_wo_outliers

gc()
```


```{r}
districts <- readRDS("data/geospatial_data/districts.RDS")  

scraped_cleaned_final <- scraped_cleaned_final %>% st_centroid()
  
advertisements_complete_districts_geocoded <- districts %>% 
  st_join(scraped_cleaned_final, join = st_contains) %>% 
  select(-municipality, -district) %>% 
  rename(district = NAME) %>% 
  mutate(district = as_factor(district),
    condition = as_factor(condition),
    type = as_factor(type),
    provision = as_factor(provision),
    certificate = as_factor(certificate),
    name_nsi = as_factor(name_nsi)
  )
```



```{r}
# save data for models
final_data <- advertisements_complete_districts_geocoded

final_data$geometry <- NULL

saveRDS(final_data, file = "data/apartments_final_data.rds")
```

```{r}
rm(list = ls())

gc()
```

```{r}
apartments_final_data <- read_rds("data/apartments_final_data.rds")
```

```{r}
index_districts <- apartments_final_data %>% 
  mutate(index = if_else(index > 0, index, NA)) %>% 
  select(district, index_mean_district) %>% 
  distinct() %>% 
  group_by(district) %>% 
  summarize(index_mean_district = mean(index_mean_district, na.rm = TRUE))

saveRDS(index_districts, "data/index_districts.RDS")
```

